[build]
builder = "dockerfile"

[deploy]
startCommand = "node combined-server.js"
healthCheckPath = "/health"
healthCheckTimeout = 30

[service]
port = 3000

[environments]
  [environments.production]
    NODE_ENV = "production"
    PORT = 3000
