[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"  # Ou "node combined-server/combined-server.js" direto

[environments]
  [environments.production]
    NODE_ENV = "production"
    PORT = 3000
